node {
    withMaven(maven:'maven') {
        stage('Checkout') {
            git url: 'https://github.com/anupamgogoi0907/spring-cloud-demo.git', branch: 'master'
        }
        stage('Build') {
            sh 'mvn clean install'
        }
        stage('Image') {
            dir ('eureka-registry') {
                def app = docker.build "eureka-registry:latest"
            }
        }
        stage ('Run') {
            docker.image("eureka-registry:latest").run('-p 8761:8761 -d --name eureka-registry')
        }

    }
}
